SMS/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
]

facultyapp/urls.py
from django.urls import path, include
from . import views
app_name = 'facultyapp'

urlpatterns =[
    path('FacultyHomePage/',views.FacultyHomePage,name="FacultyHomePage"),
    path('add_blog/',views.add_blog,name='add_blog'),
    path('<int:pk>/delete/',views.delete_blog,name='delete_blog'),
    path('add_course/',views.add_course,name='add_course'),
    path('view_student_list/',views.view_student_list,name='view_student_list'),
    path('post_marks/', views.post_marks,name='post_marks')


]

studentapp/urls.py
from django.urls import path, include
from . import views
app_name = 'studentapp'
urlpatterns = [
    path('StudentHomePage/',views.StudentHomePage,name="StudentHomePage"),
    path('view_marks/',views.view_marks,name="view_marks")



]

templates/Navbar/FacultyNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <style>
        /* Custom red background for the navbar */
        .navbar-red {
            background-color:Red !important;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-red">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_student' %}">ADD STUDENT</a>
        </li>
                  <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_course' %}">ADD COURSE TO STUDENT</a>
        </li>
                    <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:post_marks' %}">PostMarks</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_blog' %}">BlogPost</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'student_list' %}">STUDENT LIST</a>

                  <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:view_student_list' %}"> VIEW STUDENT COURSE</a>
      </ul>
      <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
    </div>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/Navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <style>
        /* Custom red background for the navbar */
        .navbar-red {
            background-color:LightBlue !important;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-red">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
            <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">ExceptionHandling</a></li>
            <li><a class="dropdown-item" href="{% url 'randompagecall' %}">Randomlogic</a></li>
              <li><a class="dropdown-item" href="{% url 'calculatorpagecall' %}">Calculator</a></li>
               <li><a class="dropdown-item" href="{% url 'datetimepagecall' %}">Date and time</a></li>
              <li><a class="dropdown-item" href="{% url 'add_task' %}">TO DO</a></li>
              <li><a class="dropdown-item" href="{% url 'upload_file' %}">GENERATE GRAPH</a></li>
              <li><a class="dropdown-item" href="{% url 'feedback' %}">FEEDBACK FORM</a></li>
              <li><a class="dropdown-item" href="{% url 'add_contact' %}">CONTACT MANAGER</a></li>
              <li><a class="dropdown-item" href="{% url 'contact_list' %}">CONTACT LIST</a></li>
          </ul>
        </li>
      </ul>
      <ul  class="navbar-nav ms-auto">
    <li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
    </div>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/Navbar/StudentNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <style>
        /* Custom red background for the navbar */
        .navbar-red {
            background-color:Violet !important;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-red">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            TRACK RECORDS
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'studentapp:view_marks' %}">View Marks</a></li>
            <li><a class="dropdown-item" href="">-</a></li>
            <li><a class="dropdown-item" href="">-</a></li>
              <li><a class="dropdown-item" href="">-</a></li>
               <li><a class="dropdown-item" href="">-</a></li>
              <li><a class="dropdown-item" href="">-</a></li>
              <li><a class="dropdown-item" href="">-</a></li>
              <li><a class="dropdown-item" href="">-</a></li>
          </ul>
        </li>
      </ul>
      <ul  class="navbar-nav ms-auto">
    <li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
    </div>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>